[workspace]
resolver = "2"
members = [
    "crates/day1",
    "crates/day2",
    "crates/day3",
    "crates/day4",
    "crates/day5",
    "crates/day6",
    "crates/day7",
    "crates/day8",
    "crates/day9",
    "crates/day10",
    "crates/day11",
]
